# Usa un'immagine con Java 22
FROM eclipse-temurin:22-jdk

# Crea una cartella dentro il container
WORKDIR /app

# Copia il jar nel container
COPY target/auth-service-0.0.1-SNAPSHOT.jar app.jar

# Espone la porta (modifica se usi una diversa in Spring Boot)
EXPOSE 8080

# Comando per eseguire l'app
ENTRYPOINT ["java", "-jar", "app.jar"]